<script lang="ts">
	import { IconButton } from '#lib/bedrock/ui/icon-button';
	import { onDestroy } from 'svelte';
	let {
		code,
		html,
		label = 'TypeScript',
		maxHeight
	}: { code: string; html: string; label?: string; maxHeight?: string } = $props();
	let copied = $state(false);
	let disposed = false;
	let failed = $state(false);
	let timer: ReturnType<typeof setTimeout> | undefined;
	async function copy() {
		copied = false;
		clearTimeout(timer);
		try {
			await navigator.clipboard.writeText(code);
			if (disposed) return;
			copied = true;
			failed = false;
			clearTimeout(timer);
			timer = setTimeout(() => {
				copied = false;
			}, 1400);
		} catch {
			if (!disposed) failed = true;
		}
	}
	onDestroy(() => {
		disposed = true;
		clearTimeout(timer);
	});
</script>

<div data-slot="highlighted-code" class="overflow-hidden rounded-xl border bg-muted/30">
	<div class="flex min-h-9 items-center justify-between gap-3 border-b bg-muted/50 px-3 py-1.5">
		<span class="font-code text-[11px] tracking-wide text-foreground/70">{label}</span>
		<IconButton
			icon={copied ? 'checkDouble' : 'copy'}
			label={copied ? 'Copied' : 'Copy code'}
			size="xs"
			onclick={copy}
		/>
	</div>
	<div
		class="highlighted-content overflow-auto font-code text-[13px] leading-relaxed"
		style:max-height={maxHeight}
	>
		<!-- HTML is escaped and generated by the server-only Shiki module, never consumer markup. -->
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		{@html html}
	</div>
	{#if failed}<p role="status" class="px-4 pb-3 text-sm">
			Copy failed. Select the code to copy it manually.
		</p>{/if}
</div>

<style>
	.highlighted-content :global(pre) {
		margin: 0;
		padding: 1rem;
		background: transparent !important;
	}
	.highlighted-content :global(.shiki),
	.highlighted-content :global(.shiki span) {
		color: var(--shiki-light);
	}
	:global(.dark) .highlighted-content :global(.shiki),
	:global(.dark) .highlighted-content :global(.shiki span) {
		color: var(--shiki-dark);
	}
</style>
